#
# i3blocks config file
#


#
# Global properties
#
command=/usr/share/i3blocks/$BLOCK_NAME
separator=false
separator_block_width=21
markup=none



#
# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
[keyindicator]
instance=CAPS
interval=once
signal=11

[keyindicator]
instance=NUM
interval=once
signal=11



#
# Volume indicator
#
[volume]
label=♪
instance=Master
interval=1
signal=10



#
# CPU load average
#
[load_average]
label=
interval=2



#
# Battery indicator
#
[battery]
label=⚡
interval=30



#
# Date Time
#
[time]
command=date '+%d/%m/%Y %H:%M:%S  '
interval=1
